#    __  __       __  __                        
#   |  \/  |     |  \/  |                       
#   | \  / |_   _| \  / | ___  _ __   ___ _   _ 
#   | |\/| | | | | |\/| |/ _ \| '_ \ / _ \ | | |
#   | |  | | |_| | |  | | (_) | | | |  __/ |_| |
#   |_|  |_|\__, |_|  |_|\___/|_| |_|\___|\__, |
#            __/ |                         __/ |
#           |___/                         |___/ 
#
# Copyright (c) 2016 Dog2puppy

general:
 - unique-files: false # Should we make each user their own <username>.yml file to store their money in? true=yes false=no (Recommended) Default: false Note: If enabled usernames that are config, users, etc will not be able to use MyMoney. This is to prevent you from loosing your configs.
