#    __  __       __  __                        
#   |  \/  |     |  \/  |                       
#   | \  / |_   _| \  / | ___  _ __   ___ _   _ 
#   | |\/| | | | | |\/| |/ _ \| '_ \ / _ \ | | |
#   | |  | | |_| | |  | | (_) | | | |  __/ |_| |
#   |_|  |_|\__, |_|  |_|\___/|_| |_|\___|\__, |
#            __/ |                         __/ |
#           |___/                         |___/ 
#
# Copyright (c) 2016 Dog2puppy

tax: 
 - time: 600 # How often should we take tax from users?
